version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ''
    ignore:
      # see tools/codegen/Cargo.toml
      - dependency-name: globset
    labels: []
