[package]
name = "portable-atomic"
version = "0.1.4"
edition = "2018"
rust-version = "1.34"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/portable-atomic"
keywords = ["atomic"]
categories = ["concurrency", "data-structures", "embedded", "no-std"]
exclude = ["/.*", "/tools"]
description = """
Portable atomic types.
"""

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
targets = ["x86_64-unknown-linux-gnu"]

[workspace]
members = [
    "bench",
    "tests/asm-test",
    "tests/no-std",
]

[features]
default = ["fallback"]

# (enabled by default) Enable fallback implementations.
#
# Disabling this allows only atomic types for which the platform natively supports atomic operations.
fallback = []

# Similar to the `i128` feature, but tries to use `cmpxchg16b` in more cases based on dynamic CPU feature detection.
#
# Note:
# - This implicitly enables the `fallback` feature.
# - Dynamic detection is only enabled in nightly, otherwise it works the same as the default.
# - When `cmpxchg16b` target feature is enabled at compile time, this works exactly the same as the default.
# - This is compatible with no-std (as with all features except `std` and `parking_lot`).
i128-dynamic = ["fallback"]

# Provide `AtomicF{32,64}`.
# Note that most of `fetch_*` operations of atomic floats are implemented using CAS loops, which can be slower than equivalent operations of atomic integers.
float = []

# TODO
# # Provides generic `atomic<t>` type.
# generic = []

# Use `std`.
std = []

# Note: serde is public dependencies.
[dependencies]
# Implements serde::{Serialize,Deserialize} for atomic types.
#
# Note:
# - The MSRV when this feature enables depends on the MSRV of serde.
serde = { version = "1.0.103", optional = true, default-features = false }

# Use parking_lot in global locks of fallback implementation.
#
# Note:
# - This is not compatible with no-std.
# - The MSRV when this feature enables depends on the MSRV of parking_lot.
parking_lot = { version = ">=0.11, <=0.12", optional = true }

[dev-dependencies]
crossbeam-utils = "0.8"
fastrand = "1"
quickcheck = { default-features = false, git = "https://github.com/taiki-e/quickcheck.git", branch = "dev" } # https://github.com/BurntSushi/quickcheck/pull/304 + https://github.com/BurntSushi/quickcheck/pull/282 + lower MSRV
serde = { version = "1", features = ["derive"] }
serde_test = "1"
static_assertions = "1"
