[build.env]
passthrough = [
    "CARGO_INCREMENTAL",
    "CARGO_NET_GIT_FETCH_WITH_CLI",
    "CARGO_NET_RETRY",
    "CARGO_PROFILE_RELEASE_CODEGEN_UNITS",
    "CARGO_PROFILE_RELEASE_LTO",
    "CARGO_TERM_COLOR",
    "CI",
    "RUST_BACKTRACE",
    "RUST_TEST_THREADS",
    "RUSTDOCFLAGS",
    "RUSTFLAGS",
    "RUSTUP_MAX_RETRIES",
]
